In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[4],[-1],[6]])
b

array([[ 4],
       [-1],
       [ 6]])

In [6]:
C = np.array([[3,-2],[7,1]])
C

array([[ 3, -2],
       [ 7,  1]])

In [7]:
D = np.array([[3,-2,0,1],[7,1,-1,2],[4,-5,1,3]])
D

array([[ 3, -2,  0,  1],
       [ 7,  1, -1,  2],
       [ 4, -5,  1,  3]])

In [8]:
a = np.zeros((1,2))
a

array([[0., 0.]])

In [9]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [12]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [14]:
B = np.array([[1.2, 3.5, 5.1],[-0.3, 1.1, -4.5]])
B

array([[ 1.2,  3.5,  5.1],
       [-0.3,  1.1, -4.5]])

In [20]:
a.shape
B.shape

(2, 3)

In [21]:
a.ndim
B.ndim

2

In [23]:
a.dtype
B.dtype

dtype('float64')

In [25]:
a.size
B.size

6